### PR TITLE
Add automaticallyAdjustContentInsets for view

### PR DESCRIPTION
**Pull request by Jasonwei1106**
#302, I was not too sure if I should put this as an attribute or just add it in props because I don't know if this is considered as a bug for ios keyboardscrollview. I will it for you to make the decision. Please let me know if I should take anything else into consideration, thank you!

### CODE REVIEW

**Comment by ashwinibm** [comment]
If https://github.com/Instawork/hyperview/issues/302#issuecomment-848655962 addresses the issue, we can close this.

**Comment by Jasonwei1106** [comment]
@ashwinibm, yes this pr is used for addressing this issue

**Review by ashwinibm — COMMENTED** [review]
Could you add the type for the new `automaticallyAdjustContentInsets` prop in `hv-view/types.js`? LGTM otherwise.

**Comment by Jasonwei1106** [comment]
Sounds great. I just modified hv-view/types.js. If you need me to change anything else, pls let me know.

**Review by ashwinibm — APPROVED** [review]
Thanks for the update!

**Pull request merged**
