### PR TITLE
chore: Deprecate `<text-area>` element

### PR DESCRIPTION
**Pull request by flochtililoch**
`<text-area>` and `<text-field>` are very close in nature, in fact they shared mostly the same code and are backed by the same underlying `TextInput` RN component. This change centralizes the logic used into `components/hv-text-field` by making `text-area` an alias of `text-field`. When the local name used is `text-area`, the `multiline` property is set automatically.
It also formally deprecates usage of `<text-area>`.

### CODE REVIEW

**Comment by adamstep** [comment]
@flochtililoch are there any features supported by `<text-field>` that weren't supported by `<text-area>`? I can think of one (`mask`), but maybe there's others. We should just test the combination of mask and multiline to make sure it works as expected.

**Comment by flochtililoch** [comment]
> it works as expected

I would assume it's not expected to work, since it's not documented as formal usage. I think it should work though, I can verify a bit later.

**Comment by adamstep** [comment]
> I would assume it's not expected to work, since it's not documented as formal usage. I think it should work though, I can verify a bit later.

`mask` is documented as formal usage: https://hyperview.org/docs/reference_textfield#mask

**Comment by flochtililoch** [comment]
I meant, `mask` is not meant to be used along with `text-area`

**Comment by adamstep** [comment]
Ah right, I think we didn't add it to `<text-area>` because there wasn't a clear use case like there is for things like SSNs, phone numbers, etc.

**Review by adamstep — APPROVED** [review]

**Comment by flochtililoch** [comment]
@adamstep I tested the mask functionality with `<text-field multiline="true">`, it work well. In my last two commits, I updated the examples and fixed the schema, can you take another look?

**Review by adamstep — APPROVED** [review]
example updates look good

**Comment by adamstep** [comment]
thanks @flochtililoch !

**Pull request merged**
