### PR TITLE
fix: `hv-switch` imports

### PR DESCRIPTION
**Pull request by flochtililoch**
Wrap RN only imports to prevent build failures

### CODE REVIEW

**Comment by adamstep** [comment]
Since `normalizeColor` doesn't do anything on the web, will this affect the UI in any way that matters?

**Comment by flochtililoch** [comment]
> Since `normalizeColor` doesn't do anything on the web, will this affect the UI in any way that matters?

It might, I honestly am not sure what we use it for. This workaround is mostly to get around build failures as the import does not exists in `react-native-web`. This might be something we revisit in the future.

**Comment by adamstep** [comment]
Got it, can we create issues for things like this where we need to add web support later?

**Review by adamstep — APPROVED** [review]

**Comment by lenwhite** [comment]
The what `normalizeColor` was used to solve in that PR is color-consistency in the switch. 

As seen in the screenshot above, the **Switch on** state had a green color (the system-default `thumbColor`) with a blue background (that was styled). https://github.com/Instawork/hyperview/pull/368 allowed the setting of the `thumbColor`, with it defaulting to a darker shade of the `backgroundColor` if not set to maintain consistency in appearance, as per the screenshots in the PR:

image


image

`normalizeColor` was used to auto-generate the background color on android devices. This functionality was limited to android only (`Platform.OS === 'android'`) though we could have it for web as well.

**Pull request merged**
