### PR TITLE
refactor(hv-date-field): functional component

### PR DESCRIPTION
**Pull request by flochtililoch**
Simplify implementation by changing component from class-based to functional, and better segregate platform-specific handling.

Sanity check on iOS demo app (note: I was not able to test on Android as the date picker in the demo app is currently broken with the demo app)

| HV Demo | Biz app Android | Biz app iOS |
|----------|---------|--------|
| hv-demo | Screenshot 2024-09-27 at 10 58 14 AM | Simulator Screenshot - iPhone 16 Pro - 2024-09-27 at 10 54 37 |

### CODE REVIEW

**Comment by adamstep** [comment]
What does it mean that the date picker is broken on Android? Is this new or an existing issue?

**Comment by flochtililoch** [comment]
> What does it mean that the date picker is broken on Android? Is this new or an existing issue?

it's an existing issue on master branch, the date picker does not work on Android in the demo app. Not sure since when this has been an issue.

**Review by adamstep — COMMENTED** [review]
Code overall looks good, but this compnent is historically one of the more brittle ones, so I'd like to make sure we have full QA confidence between platforms and modes to make sure everything works as expected.

**Comment by flochtililoch** [comment]
> Code overall looks good, but this compnent is historically one of the more brittle ones, so I'd like to make sure we have full QA confidence between platforms and modes to make sure everything works as expected.

I'll have QA done before cutting a new release

**Review by adamstep — APPROVED** [review]

**Pull request merged**
