### PR TITLE
fix: partial document error state

### PR DESCRIPTION
**Pull request by palaparthi**
PR https://github.com/Instawork/hyperview/pull/504 changed partial document error state which removed reload button, adding the reload button back.

Edit: updated screenshots based on feedback
| error state 1 | error state 2 |
| --- | --- |
| Simulator Screenshot - iPhone 13 - 2023-04-19 at 23 15 57 | Simulator Screenshot - iPhone 13 - 2023-04-19 at 23 30 27 |

### CODE REVIEW

**Comment by flochtililoch** [comment]
A couple of questions/suggestions:
- Could we adjust the layout a bit so that there's more room around the reload link? I can see this being really hard to tap on the link in both of your screenshots
- Is there a specific reason to show the URL related tot he server error? Does this happen only on dev env? I think we probably shouldn't render this in prod apps
- is the yellow background choice adequate? i.e. why not keeping it white background?

**Comment by palaparthi** [comment]
> * Could we adjust the layout a bit so that there's more room around the reload link? I can see this being really hard to tap on the link in both of your screenshots

Sounds good, I will add some padding and make the entire banner tappable as @adamstep suggested above.
> * Is there a specific reason to show the URL related tot he server error? Does this happen only on dev env? I think we probably shouldn't render this in prod apps

Yes, this is only for dev
> * is the yellow background choice adequate? i.e. why not keeping it white background?

The intention was to highlight the error specifically for the network error when the content is cached (2nd error state above), white background could feel like content rather than a warning. That being said I don't have a strong preference, I can switch it back to white if you think that's better @flochtililoch.

**Comment by palaparthi** [comment]
Screenshot with white background, what do you think @flochtililoch?
simulator_screenshot_5F89C0A6-E26E-44FD-8735-E7553B3F5B36

**Review by flochtililoch — APPROVED** [review]
I think latest changes are an improvement over what existed before, so let's get this in, thanks for the updates!

**Pull request merged**
