### PR TITLE
Fix: Set default color in all activity indicators

### PR DESCRIPTION
**Pull request by ashwinibm**
Apply default color for other `ActivityIndicators`

Reference: 
https://github.com/Instawork/hyperview/pull/275
https://github.com/Instawork/instawork/pull/13363/files#r667629321

### CODE REVIEW

**Review by flochtililoch — APPROVED** [review]

**Review by adamstep — CHANGES_REQUESTED** [review]
This is Instawork's default color. It shouldn't be hard-coded in HV.

**Comment by adamstep** [comment]
Can we use the default color per-platform? Is that what the RN spinner does by default?

**Comment by flochtililoch** [comment]
The version of RN we're using has a bug that prevents Android from using the default color on spinners. We've already taken the step to hardcode our color in #275, but that might not be the most elegant solution. Maybe we can undo #275 and instead write a patch for our RN app, so that default color is not ignored on Android.

**Comment by adamstep** [comment]
I'm ok hard-coding the defaults in HV. But ideally we can work around the RN bug by hard-coding the original default color.

**Comment by ashwinibm** [comment]
Closing in favor of using a patch in the client app instead https://github.com/Instawork/mobile/pull/3848

**Comment by ashwinibm** [comment]
Closing in favor of using a patch in the client app instead https://github.com/Instawork/mobile/pull/3848

**Pull request closed without merging**
