### PR TITLE
Support custom form input components

### PR DESCRIPTION
**Pull request by adamstep**
Addresses #355 . Each input component (standard or custom) defines a static `getFormInputValues(element: Element): Array<[string, string]>` method, which is used to gather the form data.

- All standard custom elements have been moved to use this new API.
- `getFormData()` now simply iterates through the component registry, finding all components with a `getFormInputValues` property, and calls the method on the elements within the form to create the final `FormData`.
- Added tests for each `getFormInputValues()` implementation.

### CODE REVIEW

**Comment by adamstep** [comment]
@flochtililoch I've been struggling with the Flow types here. It seems Flow doesn't like that I'm adding an optional static property to HvComponent here: https://github.com/Instawork/hyperview/pull/359/files#diff-e9726d469bba0bec8608c095ad5c361aeb95ea53afadd7ab44b462a2eb5e7467R304

As far as I know this is the right syntax, any idea what's going on?

**Comment by flochtililoch** [comment]
> any idea what's going on?

Not really, I remember running into the same issue when adding the attribute `localNameAliases` to the `HvComponentStatics`, and the only way I found to work around the problem, was to make the property a non-optional, and to define it in every `HvComponent` classes. Not the most elegant, but likely something to do with flow being outdated and buggy.

**Comment by adamstep** [comment]
> the only way I found to work around the problem, was to make the property a non-optional, and to define it in every `HvComponent` classes. Not the most elegant, but likely something to do with flow being outdated and buggy.

I see. I guess this won't affect custom components, right? Since we're not checking types at that level?

**Comment by flochtililoch** [comment]
> this won't affect custom components, right?

I think that should be fine, I don't see the `localNameAliases` on most of our custom components

**Pull request merged**
