### PR TITLE
chore(demo): Update dependencies

### PR DESCRIPTION
**Pull request by flochtililoch**
Update demo app to latest expo dependencies.

| iOS | Android | Web |
|------|--------|-------|
| Screenshot 2023-08-04 at 5 58 19 PM | Screenshot 2023-08-04 at 5 56 54 PM | Screenshot 2023-08-04 at 6 00 18 PM |

For reference, no files were manually updated, but instead the following commands were run:

```sh
mv demo/ demo-old
npx --yes create-expo-app demo --template blank
cd demo/
npx expo install @react-native-community/datetimepicker @react-native-picker/picker react-native-gesture-handler react-native-safe-area-context react-native-screens react-native-web react-native-webview
yarn add @babel/preset-env @react-navigation/bottom-tabs @react-navigation/native @react-navigation/stack @types/react moment react-dom typescript hyperview
yarn add @expo/webpack-config -D
yarn add react-native-keyboard-aware-scrollview@2.1.0 --exact
cd ..
mv demo-old/src demo
mv demo-old/App.js demo
mv demo-old/assets/* demo/assets
mv demo-old/webpack.config.js demo
mv demo-old/tsconfig.json demo
mv demo-old/README.md demo
rm -rf demo-old
rm demo/package-lock.json
```

### CODE REVIEW

**Comment by adamstep** [comment]
Will this address the issue mentioned here? https://github.com/Instawork/hyperview/discussions/602

**Comment by flochtililoch** [comment]
It might, I was getting some of these warnings and the Android app would refuse to load, which led me down that path of updating to latest.

**Comment by hgray-instawork** [comment]
Do we need to manually enforce the safe area on Android or create a safe area container? I'd have thought react-navigation would solve that.

**Comment by flochtililoch** [comment]
> Do we need to manually enforce the safe area on Android or create a safe area container? I'd have thought react-navigation would solve that.

We're using the `safe-area` param of `hv-view`, which under the hood leverages the [RN `SafeAreaView`](https://reactnative.dev/docs/safeareaview), which only works on iOS. In our apps, we handle the safe area manually (via device detection). Ideally, we should look into replacements of `SafeAreaView` to properly handle Android.

**Review by hgray-instawork — APPROVED** [review]

**Pull request merged**
