### PR TITLE
Add example to clear all & select all in a form

### PR DESCRIPTION
**Pull request by adamstep**
As a reference for @scripterkaran.

clear_select

### CODE REVIEW

**Comment by scripterkaran** [comment]
Awesome Thanks! @adamstep

**Comment by scripterkaran** [comment]
@adamstep  I think we missed a case:

1# Select any option 
2# Click Clear Selection
3# Select any option
4# Click Clear Selection -> Does not clear selection

**Comment by adamstep** [comment]
@scripterkaran it should work now. I moved the hidden view above the visible screen. That way the referenced id is first.

It's not a solution I feel great about but it works. There are some alternative solutions we can consider now or for the long run:
1. rather than replacing the fragment from the doc, make a request to the server to replace the `<select-multiple>` with a filled element or cleared element.
    - Pros: will work without any changes to the Hyperview client
    - Cons: simple interaction would require a request to the backend, which can feel like overkill
2. add a `select` and `deselect` behavior, which would change the selection state of an `<option>` element. Then, pressing "clear all" would trigger a bunch of `deselect` behaviors to change the state of the form.
    - Pros: interaction is explicit, XML is clean, everything happens on client
    - Cons: requires adding and testing a new behavior in the Hyperview client

**Comment by adamstep** [comment]
Closed in favor of the new `set-value` action: https://github.com/Instawork/hyperview/pull/98

**Pull request closed without merging**
