### PR TITLE
chore: Remove deprecated use of react-native `Picker`

### PR DESCRIPTION
**Pull request by flochtililoch**
Replace with `@react-native-picker/picker` library.

| iOS | Android |
|---|---|
|  Simulator Screen Shot - iPhone 13 - 2022-03-15 at 16 24 57 | Screen Shot 2022-03-15 at 5 08 26 PM |

### CODE REVIEW

**Review by adamstep — APPROVED** [review]
This is the project that was spun out of the core of RN, right?

**Comment by flochtililoch** [comment]
> This is the project that was spun out of the core of RN, right?

I couldn't tell from the docs ([RN Picker](https://reactnative.dev/docs/next/picker), [@react-native-picker/picker](https://github.com/react-native-picker/picker#react-native-pickerpicker)) but it's very likely given that the API is identical.

**Comment by flochtililoch** [comment]
There seem to be some issues when rendering the selected state on Android (possibly tracked [here](https://github.com/react-native-picker/picker/issues/381)), putting this on hold for now.

**Review by abdelav — APPROVED** [review]

**Comment by flochtililoch** [comment]
> There seem to be some issues when rendering the selected state on Android (possibly tracked [here](https://github.com/react-native-picker/picker/issues/381)), putting this on hold for now.

This issue does not seem to apply to our app, I'm wondering if there's an issue linked to Expo. I'll merge this for now and we can revisit if this becomes a problem.

**Pull request merged**
